### ISSUE TITLE
Fix Java path

### ISSUE THREAD

**Issue by claudiomenghi** [deib-polimi/didattica-ing-software#4]
I remember the first lecture (the past year), when they have installed java they did not have java in their path.
Are you sure that in the guid the Java JDK is added to the .profile file? 
Claudio.

**Comment by krledmno1** [comment]
Yes, good point. I'm on it. 
EDIT: I'll do it when you roll back the structure. I don't want to introduce more changes that will be cancelled (in case you agree with issue https://github.com/deib-polimi/didattica-ing-software/issues/5).

**Comment by krledmno1** [comment]
Done (with screenshots :) )

**Comment by alessandrorizzi** [comment]
By the way, I updated the guide for Java 8 (and Eclipse Mars) but I have only tested the new version on Linux.

**Comment by krledmno1** [comment]
I can test it on OS X, but we need someone to test it on Win. Gibbo?
