### ISSUE TITLE
Repo organization

### ISSUE THREAD

**Issue by krledmno1** [deib-polimi/didattica-ing-software#5]
Could we revert back to having a fixed root structure:

├── Exercises
│   ├── 01\ -\ Introduction
│   ├── 02\ -\ Java\ Types,\ Operators\ and\ Array
│   ├── 03\ -\ Inheritance
│   ├── etc ...
└── Lab
    ├── Instructions
    ├── Session\ 1\ 
    ├── Session\ 2\ 
    ├── Session\ 3\ 
    ├── etc ...

and then have branches for 2015, 2016 and master. Obviously, merging 2016 with master on every stable change and keeping 2015 just as a label. 

I think it's unnecessary to create svn-like branches and then recreate the structure and copy files to start over. Especially because you loose change history for each file. 

What do you think?

**Comment by claudiomenghi** [comment]
Ok. Just keep the files in the 2016 folder as it is since I have already changes some of them (and also Alessandro I guess)…

**Comment by krledmno1** [comment]
Done! I made sure to include your changes to 01.tex and Ale's change in Eclipse.tex

The folder structure is the same 
├── Exercises
│   ├── 01\ -\ Introduction
│   ├── 02\ -\ Java\ Types,\ Operators\ and\ Array
│   ├── 03\ -\ Inheritance
│   ├── etc ...
└── Lab
&nbsp;&nbsp;&nbsp;&nbsp;├── Session\ 1\ 
&nbsp;&nbsp;&nbsp;&nbsp;├── Session\ 2\ 
&nbsp;&nbsp;&nbsp;&nbsp;├── Session\ 3\ 
&nbsp;&nbsp;&nbsp;&nbsp;├── etc ... 

The commit graph is the following: 

C1<- C2 <- C3 <- ... Cn <- ... <- Cm
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2015&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2016 and master

And the workflow is: 
git pull -all
git checkout 2016 
...do some changes...
git checkout master
git merge
git push -all

This way we keep master and 2016 branches synced.

If you want to see the 2015 version of a file do
git checkout 2015
